# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile is used to provision a development environment with support for the following libraries:
#   - CVC4 (see http://cvc4.cs.nyu.edu/web/)
#
# It can be used to run all tests within a development environment (e.g. via `cd /vagrant; sbt test`)

# If no CVC4 commit value/version is specified, we build `master`
VERSION = ENV["VERSION"] || "master"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu-trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  # Ensure that the image is provisioned with:
  #   - JDK 7 (current CVC4 JNI binding requirement)
  #   - SBT
  #   - CVC4 (with Java JNI bindings)
  config.vm.provision "shell", inline: <<-SHELL
    echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt.list
    sudo apt-get -y update
    sudo apt-get install -y git autoconf libtool
    sudo apt-get install -y libgmp-dev antlr3 libantlr3c-dev libboost-dev libboost-thread-dev swig2.0 libcln-dev openjdk-7-jdk
    sudo apt-get install -y --force-yes sbt cxxtest

    cd /tmp
    git clone -b #{VERSION} https://github.com/CVC4/CVC4.git cvc4
    cd cvc4

    export JAVA_CPPFLAGS=-I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include/
    export DEBVERSION="1.4.1~`date +%Y%m%d`"

    ./autogen.sh
    ./configure --prefix=/usr --enable-unit-testing --enable-proof --with-portfolio --enable-language-bindings=java
    make
    make check
    make install

    cp ./builds/x86_64-unknown-linux-gnu/production-proof/src/bindings/CVC4.jar /vagrant/exercise-query/lib
  SHELL
end
